# Generated by Django 5.2.3 on 2025-06-27 11:31

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("date_of_birth", models.DateField()),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("IT", "IT"), ("HR", "HR"), ("Finance", "Finance")],
                        max_length=20,
                    ),
                ),
                (
                    "resume_file_id",
                    models.CharField(
                        help_text="File ID from upload endpoint", max_length=255
                    ),
                ),
                ("resume_filename", models.CharField(max_length=255)),
                ("resume_url", models.URLField(help_text="Permanent resume file URL")),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "candidates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["department"], name="candidates_departm_eafc5a_idx"
                    ),
                    models.Index(
                        fields=["current_status"], name="candidates_current_ea525d_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="candidates_created_e15ebe_idx"
                    ),
                    models.Index(fields=["email"], name="candidates_email_32f680_idx"),
                    models.Index(fields=["phone"], name="candidates_phone_49e098_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("admin_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="candidates.candidate",
                    ),
                ),
            ],
            options={
                "db_table": "candidate_status_history",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate", "-changed_at"],
                        name="candidate_s_candida_83ab7e_idx",
                    )
                ],
            },
        ),
    ]
