# Generated by Django 5.2.3 on 2025-06-27 11:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemporaryFileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_id", models.CharField(max_length=255, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size", models.PositiveIntegerField()),
                ("storage_info", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "temporary_file_uploads",
                "indexes": [
                    models.Index(
                        fields=["file_id"], name="temporary_f_file_id_2db91e_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="temporary_f_expires_c755a7_idx"
                    ),
                    models.Index(
                        fields=["is_used"], name="temporary_f_is_used_f09dba_idx"
                    ),
                ],
            },
        ),
    ]
